### PR TITLE
speed up Pol.Deg with a lookup table

### PR DESCRIPTION
**Pull request by ncleaton**
This speeds up Pol.Deg() by more than 50%, but that only works out at a 13% speed improvement for RandomPolynomial(), so maybe it's not worthwhile, not sure.

I've only tested it on my laptop, other CPUs may vary

### CODE REVIEW

**Comment by fd0** [comment]
Hey, thanks for your contribution! I've thought about making this function more efficient when initially implementing the chunker, but decided it wasn't worth the effort. The function `Deg()` is not called in hot loops in the chunker code itself, it is only used during initialization and reset (which I'm not using that much in restic).

What's your use case?

**Comment by ncleaton** [comment]
> decided it wasn't worth the effort. The function `Deg()` is not called in hot loops in the chunker code

That's pretty much what I thought, but having found the speedup I wanted to offer it to you. Feel free to close this merge request.

> What's your use case?

I don't have a use case that requires this to be merged.

I'm trying to attack the restic chunker from the viewpoint of an attacker who has observed some cutpoints on known data and wants to recover the chunker polynomial. I'm starting by seeing how long pure brute force would take, which lead me to make Mod() run as fast as I can.

**Comment by fd0** [comment]
Thanks for the feedback! Then I'll close this PR in favor of keeping the code simpler. Thanks a lot though!

> I'm trying to attack the restic chunker from the viewpoint of an attacker who has observed some cutpoints on known data and wants to recover the chunker polynomial. I'm starting by seeing how long pure brute force would take, which lead me to make Mod() run as fast as I can.

Interesting! I never got around to actually doing that, please keep me posted what you find! :)

**Comment by ncleaton** [comment]
> > I'm trying to attack the restic chunker from the viewpoint of an attacker who has observed some cutpoints on known data and wants to recover the chunker polynomial.
> 
> Interesting! I never got around to actually doing that, please keep me posted what you find! :)

I emailed you the details, but I 'm not sure if I have the right address. In summary, with 25 or more observed cutpoints I found a way to recover the polynomial with a few minutes of computation.

**Pull request closed without merging**
